# Generated by Django 5.0.3 on 2024-05-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('vagas_carros', models.IntegerField(default=0)),
                ('vagas_motos', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTOCICLETA', 'Motocicleta')], max_length=50)),
                ('ocupada', models.BooleanField(default=False)),
                ('estacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.estacionamento')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTOCICLETA', 'Motocicleta')], default='CARRO', max_length=50)),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monolith.vaga')),
            ],
        ),
    ]
