# Generated by Django 5.0.3 on 2024-03-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='tipo',
        ),
    ]
