# Generated by Django 5.0.3 on 2024-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0002_alter_estacionamento_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='cnpj',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
