# Generated by Django 5.0.3 on 2024-05-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0004_alter_estacionamento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
